// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/later.h"
#include <Rcpp.h>

using namespace Rcpp;

// ensureInitialized
void ensureInitialized();
RcppExport SEXP _later_ensureInitialized() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    ensureInitialized();
    return R_NilValue;
END_RCPP
}
// execCallbacks
bool execCallbacks(double timeoutSecs, int loop);
RcppExport SEXP _later_execCallbacks(SEXP timeoutSecsSEXP, SEXP loopSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type timeoutSecs(timeoutSecsSEXP);
    Rcpp::traits::input_parameter< int >::type loop(loopSEXP);
    rcpp_result_gen = Rcpp::wrap(execCallbacks(timeoutSecs, loop));
    return rcpp_result_gen;
END_RCPP
}
// idle
bool idle(int loop);
RcppExport SEXP _later_idle(SEXP loopSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type loop(loopSEXP);
    rcpp_result_gen = Rcpp::wrap(idle(loop));
    return rcpp_result_gen;
END_RCPP
}
// execLater
void execLater(Rcpp::Function callback, double delaySecs, int loop);
RcppExport SEXP _later_execLater(SEXP callbackSEXP, SEXP delaySecsSEXP, SEXP loopSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Function >::type callback(callbackSEXP);
    Rcpp::traits::input_parameter< double >::type delaySecs(delaySecsSEXP);
    Rcpp::traits::input_parameter< int >::type loop(loopSEXP);
    execLater(callback, delaySecs, loop);
    return R_NilValue;
END_RCPP
}
// next_op_secs
double next_op_secs(int loop);
RcppExport SEXP _later_next_op_secs(SEXP loopSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type loop(loopSEXP);
    rcpp_result_gen = Rcpp::wrap(next_op_secs(loop));
    return rcpp_result_gen;
END_RCPP
}
