# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testCallbackOrdering <- function() {
    invisible(.Call('_later_testCallbackOrdering', PACKAGE = 'later'))
}

log_level <- function(level) {
    .Call('_later_log_level', PACKAGE = 'later', level)
}

ensureInitialized <- function() {
    invisible(.Call('_later_ensureInitialized', PACKAGE = 'later'))
}

setCurrentRegistryXptr <- function(registry_xptr) {
    invisible(.Call('_later_setCurrentRegistryXptr', PACKAGE = 'later', registry_xptr))
}

getCurrentRegistryXptr <- function() {
    .Call('_later_getCurrentRegistryXptr', PACKAGE = 'later')
}

deleteCallbackRegistry <- function(registry_xptr) {
    .Call('_later_deleteCallbackRegistry', PACKAGE = 'later', registry_xptr)
}

createCallbackRegistry <- function(parent_loop_xptr) {
    .Call('_later_createCallbackRegistry', PACKAGE = 'later', parent_loop_xptr)
}

existsCallbackRegistry <- function(registry_xptr) {
    .Call('_later_existsCallbackRegistry', PACKAGE = 'later', registry_xptr)
}

list_queue_ <- function(registry_xptr) {
    .Call('_later_list_queue_', PACKAGE = 'later', registry_xptr)
}

execCallbacks <- function(timeoutSecs, runAll, registry_xptr) {
    .Call('_later_execCallbacks', PACKAGE = 'later', timeoutSecs, runAll, registry_xptr)
}

idle <- function(registry_xptr) {
    .Call('_later_idle', PACKAGE = 'later', registry_xptr)
}

execLater <- function(callback, delaySecs, registry_xptr) {
    .Call('_later_execLater', PACKAGE = 'later', callback, delaySecs, registry_xptr)
}

cancel <- function(callback_id_s, registry_xptr) {
    .Call('_later_cancel', PACKAGE = 'later', callback_id_s, registry_xptr)
}

nextOpSecs <- function(registry_xptr) {
    .Call('_later_nextOpSecs', PACKAGE = 'later', registry_xptr)
}

