# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testCallbackOrdering <- function() {
    invisible(.Call('_later_testCallbackOrdering', PACKAGE = 'later'))
}

ensureInitialized <- function() {
    invisible(.Call('_later_ensureInitialized', PACKAGE = 'later'))
}

existsCallbackRegistry <- function(loop) {
    .Call('_later_existsCallbackRegistry', PACKAGE = 'later', loop)
}

createCallbackRegistry <- function(loop) {
    .Call('_later_createCallbackRegistry', PACKAGE = 'later', loop)
}

deleteCallbackRegistry <- function(loop) {
    .Call('_later_deleteCallbackRegistry', PACKAGE = 'later', loop)
}

execCallbacks <- function(timeoutSecs, runAll, loop) {
    .Call('_later_execCallbacks', PACKAGE = 'later', timeoutSecs, runAll, loop)
}

idle <- function(loop) {
    .Call('_later_idle', PACKAGE = 'later', loop)
}

execLater <- function(callback, delaySecs, loop) {
    invisible(.Call('_later_execLater', PACKAGE = 'later', callback, delaySecs, loop))
}

nextOpSecs <- function(loop) {
    .Call('_later_nextOpSecs', PACKAGE = 'later', loop)
}

